### ISSUE TITLE
プロンプト用ファイルの作成

### ISSUE THREAD

**Issue by YoungmanCH** [YoungmanCH/LiveTrancer#43]
@doguto 
1. プロンプトの複数パターンの作成
2. microservices/chatgpt_service/src　以下にて　AIのpromptファイルを作成

**Comment by doguto** [comment]
一応作りましたが…
Flag変数でプロンプト取得なので分かりづらいかもしれないです

**Comment by doguto** [comment]
ディレクトリ間違えてます。後で修正します。

**Comment by YoungmanCH** [comment]
@doguto 
了解です！。僕も先ほど、stt, text transcription, tts, sts全てリファクタリングしたので、一旦、最新のデータをプルしてから、再度、promptを指定してもらってもいいですか？

text_to_chatgpt.pyファイルの三行目にグローバル変数でプロンプトを指定しているので、このファイルをいじっちゃってOKです。

**Comment by YoungmanCH** [comment]
@doguto 

追記：
ディレクトリは、こちらでお願いします。

microservices/chatgpt_service/src

ファイル名は、prompt.pyみたいな、わかりやすいものであれば大丈夫です。

**Comment by doguto** [comment]
プロンプトの設定しました。
無人レジとコールセンターに関しては状況次第過ぎて変換が難しかったので以前言われたものしか実装できてません。

**Comment by YoungmanCH** [comment]
了解です。mergeしました。
